# Generated by Django 4.0.8 on 2023-01-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medidores',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('llave_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mediciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('consumo_reg', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('medidor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medidores.medidores')),
            ],
        ),
    ]
