# Generated by Django 4.0.8 on 2023-01-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediciones',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medidores',
            name='Id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
