# Generated by Django 4.0.8 on 2023-01-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidores', '0002_alter_mediciones_id_alter_medidores_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidores',
            name='llave_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medidores',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
